# Generated by Django 4.2.11 on 2024-04-10 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('palettes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hex_code', models.CharField(max_length=7)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('palette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='palettes.palette')),
            ],
        ),
    ]
